#
# MAINTAINER        Steve <daneiyunzhijia@163.com>
# DOCKER-VERSION    1.12.1
#
# Dockerizing CentOS7: Dockerfile for building CentOS images
#
FROM       centos:latest
MAINTAINER Steve <daneiyunzhijia@163.com>

ENV TZ "Asia/Shanghai"
ENV TERM xterm
